# Generated by Django 4.2.5 on 2023-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='principal',
            name='CollegeID',
        ),
        migrations.DeleteModel(
            name='college',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
