# Generated by Django 4.2.5 on 2023-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_menucategory_remove_menu_cuisine_remove_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
