# Generated by Django 4.2.5 on 2023-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_customer_vehicle_delete_menu_delete_menucategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
